version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: foursale-postgres
    environment:
      POSTGRES_DB: foursale
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: foursale-backend
    environment:
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: foursale
      DB_USER: postgres
      DB_PASSWORD: password
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  frontend:
    build: ./frontend
    container_name: foursale-frontend
    ports:
      - "80:8080"
    depends_on:
      - backend

volumes:
  postgres_data: