global:
  imageRegistry: ""
  imagePullSecrets: []

replicaCount: 2

image:
  backend:
    repository: foursale/backend
    tag: "latest"
    pullPolicy: IfNotPresent
  frontend:
    repository: foursale/frontend
    tag: "latest"
    pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: "foursale-app"

podAnnotations: {}

podSecurityContext:
  fsGroup: 1001
  runAsNonRoot: true
  runAsUser: 1001

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1001

service:
  type: ClusterIP
  backend:
    port: 3000
  frontend:
    port: 80

ingress:
  enabled: true
  className: "alb"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/ssl-redirect: '443'
  hosts:
    - host: foursale.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: foursale-tls
      hosts:
        - foursale.example.com

resources:
  backend:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  frontend:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - foursale-chart
        topologyKey: kubernetes.io/hostname

database:
  host: "foursale-postgres.rds.amazonaws.com"
  port: 5432
  name: "foursale"
  username: "postgres"
  existingSecret: "foursale-db-secret"
  secretKey: "password"

monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s
    path: /metrics

networkPolicy:
  enabled: true