name: Deploy Monitoring

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - prod

jobs:
  deploy-monitoring:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.environment == 'dev' && 'us-west-2' || 'us-east-1' }}
      
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region ${{ github.event.inputs.environment == 'dev' && 'us-west-2' || 'us-east-1' }} --name foursale-${{ github.event.inputs.environment }}
      
      - name: Deploy monitoring stack
        run: |
          chmod +x monitoring/install.sh
          ./monitoring/install.sh